"""Adição de index na tabela e parametro onupdate para update_at

Revision ID: 12323142c780
Revises: 
Create Date: 2026-03-19 13:54:36.565693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12323142c780'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tarefas_concluido_created', 'tarefas', ['concluido', 'created_at'], unique=False)
    op.create_index('idx_tarefas_titulo', 'tarefas', ['titulo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tarefas_titulo', table_name='tarefas')
    op.drop_index('idx_tarefas_concluido_created', table_name='tarefas')
    # ### end Alembic commands ###
